use super::{
    dotenv_escape, format_env_file, prepare_installed_service_deployment, print_provider_envs,
};
use crate::execution_output::ExecutionOutput;
use crate::{
    app::types::{AppRecord, AppValue, ScriptHook},
    cli::node::{NodeAddArgs, add_node_record, nodes_file},
    node::types::{NodeRecord, RemoteNodeRecord},
    provider::DeploymentTarget,
    store::duck::{InstalledServiceRecord, save_deployment_record},
};
use serde_json::json;
use std::collections::BTreeMap;
use std::{
    env,
    path::PathBuf,
    time::{SystemTime, UNIX_EPOCH},
};
use tokio::fs;

#[test]
fn print_provider_envs_lists_services_and_values_in_order() {
    let envs = BTreeMap::from([
        (
            "api".to_string(),
            BTreeMap::from([
                ("INS_APP_NAME".to_string(), "backend".to_string()),
                ("INS_NODE_NAME".to_string(), "local".to_string()),
            ]),
        ),
        (
            "worker".to_string(),
            BTreeMap::from([("INS_APP_NAME".to_string(), "jobs".to_string())]),
        ),
    ]);

    let output = ExecutionOutput::buffered();
    print_provider_envs(&envs, &output);

    let snap = output.snapshot();
    assert!(snap.contains("Provider Environment Variables:"));
    assert!(snap.contains("  [api]"));
    assert!(snap.contains("    INS_APP_NAME=backend"));
    assert!(snap.contains("    INS_NODE_NAME=local"));
    assert!(snap.contains("  [worker]"));
    assert!(snap.contains("    INS_APP_NAME=jobs"));
    // api appears before worker (BTreeMap iteration order)
    let api_pos = snap.find("[api]").expect("api present");
    let worker_pos = snap.find("[worker]").expect("worker present");
    assert!(api_pos < worker_pos, "expected api before worker: {snap}");
}

#[test]
fn dotenv_escape_double_quotes_and_escapes_specials() {
    assert_eq!(dotenv_escape("simple"), "\"simple\"");
    assert_eq!(
        dotenv_escape(r#"has "quotes" and \back"#),
        "\"has \\\"quotes\\\" and \\\\back\""
    );
    assert_eq!(dotenv_escape("line1\nline2"), "\"line1\\nline2\"");
    assert_eq!(dotenv_escape(""), "\"\"");
}

#[test]
fn format_env_file_sorts_keys_and_escapes_values() {
    let envs = BTreeMap::from([
        ("B_KEY".to_string(), "value with spaces".to_string()),
        ("A_KEY".to_string(), "simple".to_string()),
    ]);
    let out = format_env_file(&envs);
    assert!(out.contains("# Generated by ins"));
    let a_pos = out.find("A_KEY=").expect("A_KEY present");
    let b_pos = out.find("B_KEY=").expect("B_KEY present");
    assert!(a_pos < b_pos, "A should come before B: {out}");
    assert!(out.contains("A_KEY=\"simple\""));
    assert!(out.contains("B_KEY=\"value with spaces\""));
}

#[test]
fn print_provider_envs_handles_empty_maps() {
    let output = ExecutionOutput::buffered();
    print_provider_envs(&BTreeMap::new(), &output);
    let snap = output.snapshot();
    assert!(snap.contains("Provider Environment Variables:"));
    assert!(snap.contains("  (none)"));
}

#[tokio::test]
async fn prepare_installed_service_deployment_reuses_saved_service_and_values() -> anyhow::Result<()>
{
    let home = unique_test_dir("pipeline-installed-service");
    let app_dir = home.join("app").join("demo");
    fs::create_dir_all(&app_dir).await?;
    fs::write(
        app_dir.join("qa.yaml"),
        r#"
name: demo
values:
  - name: image
    type: string
  - name: port
    type: number
"#
        .trim_start(),
    )
    .await?;

    let node = NodeRecord::Remote(RemoteNodeRecord {
        name: "node-a".into(),
        ip: "10.0.0.1".into(),
        port: 22,
        user: "root".into(),
        password: "secret".into(),
        key_path: None,
    });
    add_node_record(
        &nodes_file(&home),
        NodeAddArgs {
            name: "node-a".into(),
            ip: "10.0.0.1".into(),
            port: 22,
            user: "root".into(),
            password: "secret".into(),
            key_path: None,
        },
    )
    .await?;
    let target = DeploymentTarget::new(
        AppRecord {
            name: "demo".into(),
            version: None,
            description: None,
            order: None,
            author_name: None,
            author_email: None,
            dependencies: vec![],
            before: ScriptHook::default(),
            after: ScriptHook::default(),
            volumes: vec![],
            all_volume: false,
            files: None,
            values: vec![
                AppValue {
                    name: "image".into(),
                    value_type: "string".into(),
                    description: None,
                    value: Some(json!("nginx:1.27")),
                    default: None,
                    options: vec![],
                },
                AppValue {
                    name: "port".into(),
                    value_type: "number".into(),
                    description: None,
                    value: Some(json!(8080)),
                    default: None,
                    options: vec![],
                },
            ],
        },
        "demo-web".into(),
    );
    save_deployment_record(
        &home,
        &node,
        PathBuf::from("/srv/demo").as_path(),
        &target,
        "default",
        "name: demo\nvalues: []\n",
    )
    .await?;

    let prepared = prepare_installed_service_deployment(
        &home,
        &crate::config::InsConfig::default(),
        Some("docker-compose".into()),
        &InstalledServiceRecord {
            service: "demo-web".into(),
            namespace: "default".into(),
            app_name: "demo".into(),
            node_name: "node-a".into(),
            workspace: "/srv/demo".into(),
            created_at_ms: 1,
        },
    )
    .await?;

    assert_eq!(prepared.targets.len(), 1);
    assert_eq!(prepared.targets[0].service, "demo-web");
    assert_eq!(
        prepared.targets[0].app.values[0].value,
        Some(json!("nginx:1.27"))
    );
    assert_eq!(prepared.targets[0].app.values[1].value, Some(json!(8080)));

    fs::remove_dir_all(&home).await?;
    Ok(())
}

#[tokio::test]
async fn copy_apps_to_workspace_rewrites_compose_volumes_and_returns_resolved() -> anyhow::Result<()>
{
    use crate::pipeline::copy_apps_to_workspace_with_output;
    use crate::provider::DeploymentTarget;

    let home = unique_test_dir("pipeline-volume-inject");
    let app_dir = home.join("app").join("vol-demo");
    fs::create_dir_all(&app_dir).await?;
    fs::write(
        app_dir.join("qa.yaml"),
        "name: vol-demo\nvalues: []\nvolumes:\n  - data\n",
    )
    .await?;
    fs::write(
        app_dir.join("docker-compose.yml"),
        "services:\n  web:\n    image: nginx\n    volumes:\n      - data:/var/lib/app\n",
    )
    .await?;

    let node = NodeRecord::Local();
    let workspace = home.join("workspace");
    let target = DeploymentTarget::new(
        AppRecord {
            name: "vol-demo".into(),
            version: None,
            description: None,
            order: None,
            author_name: None,
            author_email: None,
            dependencies: vec![],
            before: ScriptHook::default(),
            after: ScriptHook::default(),
            values: vec![],
            volumes: vec!["data".into()],
            all_volume: false,
            files: None,
        },
        "vol-demo".into(),
    );

    let volumes_config = vec![crate::volume::types::VolumeRecord::Filesystem(
        crate::volume::types::FilesystemVolume {
            name: "data".into(),
            node: "local".into(),
            path: "/mnt/data".into(),
        },
    )];

    let probe_cache = std::sync::Arc::new(crate::pipeline::ProbeCache::new(node.clone()));
    let resolved = copy_apps_to_workspace_with_output(
        &home,
        std::slice::from_ref(&target),
        &home.join("app"),
        &workspace,
        &node,
        &volumes_config,
        &probe_cache,
        &crate::execution_output::ExecutionOutput::stdout(),
        "default",
    )
    .await?;

    assert_eq!(resolved.len(), 1);
    assert_eq!(resolved[0].docker_name, "ins_data");

    let rendered =
        fs::read_to_string(workspace.join("vol-demo").join("docker-compose.yml")).await?;
    assert!(rendered.contains("external: true"));
    assert!(rendered.contains("ins_data"));

    fs::remove_dir_all(&home).await?;
    Ok(())
}

#[tokio::test]
async fn copy_apps_to_workspace_adds_metadata_labels_to_docker_compose_yml() -> anyhow::Result<()> {
    use crate::pipeline::copy_apps_to_workspace_with_output;

    let home = unique_test_dir("pipeline-labels");
    let app_dir = home.join("app").join("label-demo");
    fs::create_dir_all(&app_dir).await?;
    fs::write(app_dir.join("qa.yaml"), "name: label-demo\nvalues: []\n").await?;
    fs::write(
        app_dir.join("docker-compose.yml"),
        "services:\n  web:\n    image: nginx\n",
    )
    .await?;

    let node = NodeRecord::Local();
    let workspace = home.join("workspace");
    let target = DeploymentTarget::new(
        AppRecord {
            name: "label-demo".into(),
            version: None,
            description: None,
            order: None,
            author_name: None,
            author_email: None,
            dependencies: vec![],
            before: ScriptHook::default(),
            after: ScriptHook::default(),
            values: vec![],
            volumes: vec![],
            all_volume: false,
            files: None,
        },
        "label-demo".into(),
    );

    let probe_cache = std::sync::Arc::new(crate::pipeline::ProbeCache::new(node.clone()));
    copy_apps_to_workspace_with_output(
        &home,
        std::slice::from_ref(&target),
        &home.join("app"),
        &workspace,
        &node,
        &[],
        &probe_cache,
        &crate::execution_output::ExecutionOutput::stdout(),
        "staging",
    )
    .await?;

    let rendered =
        fs::read_to_string(workspace.join("label-demo").join("docker-compose.yml")).await?;
    assert!(
        rendered.contains("ins.service:"),
        "expected ins.service label in:\n{rendered}"
    );
    assert!(
        rendered.contains("ins.namespace:"),
        "expected ins.namespace label in:\n{rendered}"
    );
    assert!(
        rendered.contains("staging"),
        "expected namespace value 'staging' in:\n{rendered}"
    );

    fs::remove_dir_all(&home).await?;
    Ok(())
}

fn unique_test_dir(name: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time before unix epoch")
        .as_nanos();
    env::temp_dir().join(format!("ins-{name}-{}-{nanos}", std::process::id()))
}
